# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-21 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobicashapp', '0002_auto_20200221_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sku',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='taxcode',
        ),
        migrations.RemoveField(
            model_name='project',
            name='upc',
        ),
    ]
